image: node:20

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - yarn install
              - yarn start:server &
              - sleep 5
              - yarn test:online
            artifacts:
              - test-report.html
        - step:
            name: Code Linting
            caches:
              - node
            script:
              - yarn install
              - yarn eslint . 
    - step:
        name: Mirror to GitHub
        script:
          - mkdir -p ~/.ssh
          - echo "${SSH_KEY_ARMC}" | base64 --decode > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan github.com >> ~/.ssh/known_hosts
          - git remote add github-mirror git@github.com:UFPE-Plataformas-Dist-2025/agenda-de-compromissos-http.git
          - git push --all github-mirror